version: '3'

services:
  django:
    command: uwsgi --ini uwsgi.ini
    environment:
      - DJANGO_ENV=prod
    volumes:
      - ./socket:/socket
      - ./kaye_tech/backend/fixtures:/kaye_tech/backend/fixtures
    depends_on:
      - nginx

  nginx:
    build:
      args:
        DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      context: .
      dockerfile: dockerfiles/nginx.Dockerfile
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
    ports:
      - 2901:80
