version: "3"

services:
  db:
    image: postgres
    volumes:
            - ./kaye_tech/backend/fixtures:/kaye_tech/backend/fixtures
  django:
    build:
      context: .
      dockerfile: dockerfiles/django.Dockerfile
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - SOCIAL_AUTH_GOOGLE_OAUTH2_KEY=${SOCIAL_AUTH_GOOGLE_OAUTH2_KEY}
      - SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET=${SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET}
    restart: on-failure
    depends_on:
      - db
  redis:
    container_name: redis
    image: redis
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
